version: 2

sources: 
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of greenweez 
        columns:
          - name: date_date
            description: date of purchase
            tests:
              - not_null
          - name: orders_id
            tests:
              - not_null 
          - name: pdt_id
            tests:
              - not_null
          - name: revenue
            tests:
              - not_null
          - name: quantity
            tests:
              - not_null
        tests:
          - unique:
              column_name: "(orders_id || '_' || pdt_id)"
      - name: product
        identifier: raw_gz_product
        description: products catalog of greenweez - each line is a product
        columns:
          - name: products_id
            description: primary key
            tests:
              - unique
              - not_null
          - name: purchase_price
      - name: ship
        identifier: raw_gz_ship
        description: ship og greenweez - each line is a parcel per order
        columns:
          - name: orders_id
            description: primary key
            tests:
              - unique
              - not_null
          - name: shipping_fee
            tests:
              - not_null
          - name: logcost
            tests:
              - not_null
          - name: ship_cost
            tests:
              - not_null
      - name: adwords
        identifier: raw_gz_adwords
        description: adwords campaign for greenweez
        columns:
          - name: date_date
            tests:
              - not_null
          - name: paid_source
            tests:
              - not_null
          - name: campaign_key
            tests:
              - not_null
          - name: campaign_name
          - name: ads_cost
            tests:
              - not_null
          - name: impression
            tests:
              - not_null
          - name: click
            tests:
              - not_null
        tests:
          - unique:
              column_name: "(date_date || '_' || paid_source || '_' || campaign_key)"

      - name: bing
        identifier: raw_gz_bing
        description: bing campaign for greenweez
        columns:
          - name: date_date
            tests:
              - not_null
          - name: paid_source
            tests:
              - not_null
          - name: campaign_key
            tests:
              - not_null
          - name: campaign_name
          - name: ads_cost
            tests:
              - not_null
          - name: impression
            tests:
              - not_null
          - name: click
            tests:
              - not_null
        tests:
          - unique:
              column_name: "(date_date || '_' || paid_source || '_' || campaign_key)"
      - name: criteo
        identifier: raw_gz_criteo
        description: criteo campaign for greenweez
        columns:
          - name: date_date
            tests:
              - not_null
          - name: paid_source
            tests:
              - not_null
          - name: campaign_key
            tests:
              - not_null
          - name: campaign_name
          - name: ads_cost
            tests:
              - not_null
          - name: impression
            tests:
              - not_null
          - name: click
            tests:
              - not_null
        tests:
          - unique:
              column_name: "(date_date || '_' || paid_source || '_' || campaign_key)"
      - name: facebook
        identifier: raw_gz_facebook
        description: facebook campaign for greenweez
        columns:
          - name: date_date
            tests:
              - not_null
          - name: paid_source
            tests:
              - not_null
          - name: campaign_key
            tests:
              - not_null
          - name: campaign_name
          - name: ads_cost
            tests:
              - not_null
          - name: impression
            tests:
              - not_null
          - name: click
            tests:
              - not_null
        tests:
          - unique:
              column_name: "(date_date || '_' || paid_source || '_' || campaign_key)"

models:
      - name: stg_raw_product
        description: cleaning of product table cointaing product catalogue

      - name: stg_raw_sales
        description: cleaning of sales table containing all orders

      - name: stg_raw_ship
        description: cleaning of shippment table, containing all parcels

      - name: stg_raw__adwords
        description: adwords greenweez campain

      - name: stg_raw__bing
        description: bing greenweez campain

      - name: stg_raw__criteo
        description: criteo greenweez campain

      - name: stg_raw__facebook
        description: facebook greenweez campain

      - name: int_sales_margin
        description: margin calcultation
        tests:
        - unique:
            column_name: "(orders_id || '-' || products_id)"
        - not_null:
            column_name:
              - products_id
              - date_date
              - orders_id
              - revenue
              - quantity
              - purchase_price
              - purchase_cost
              - margin

      - name: int_orders_margin
        description: margin calcultation per order 
        columns:
          - name: orders_id
            description: primary key
            tests:
              - unique
              - not_null
          - name: date_date
            description: date client placed order
            test:
              - not_null
          - name: revenue
            description: revenue from order
            test:
              - not_null
          - name: quantity 
            description: quantity of items purchased per order
            test:
              - not_null 
          - name: purchase_cost
            description: cost of each product per order
            test:
              - not_null
          - name: margin
            description: revenue minus costs
            test:
              - not_null 

      - name: int_orders_operational
        description: operational margin calcultation per order 
        columns:
            - name: orders_id
              description: unique identifier of each order
              tests:
                - unique
                - not_null
            - name: date_date
              description: date client placed order
              test:
                - not_null
            - name: revenue
              description: revenue from order
              test:
                - not_null
            - name: quantity
              description: quantity of items purchased
              test:
                - not_null
            - name: purchase_cost
              description: Purchase_cost = Quantity * Purchase_price
              test:
                - not_null
            - name: margin
              description: Margin = Revenue - Purchase_cost
              test:
                - not_null
            - name: operational_margin
              description: margin + shipping fee - log_cost - ship_cost
              test:
                - not_null
            - name: ship_cost
              description: cost paid by company for shipping per order 
              test:
                - not_null
            - name: shipping_fee
              description: priced paid by client for shipping per order
              test:
                - not_null
            - name: logcost
              description: logistics cost for the company per order
              test:
                - not_null
          
      - name: int_campaigns
        description: integration of all campaigns
        columns:
          - name: date_date
            tests:
              - not_null
          - name: paid_source
            tests:
              - not_null
          - name: campaign_key
            tests:
              - not_null
          - name: campaign_name
          - name: ads_cost
            tests:
              - not_null
          - name: impression
            tests:
              - not_null
          - name: click
            tests:
              - not_null
        tests:
          - unique:
              column_name: "(date_date || '_' || paid_source || '_' || campaign_key)"

      - name: int_campaigns_days
        description: integration of all campaigns grouped by day
        columns:
          - name: date_date
            tests:
              - unique
              - not_null
          - name: ads_cost
            tests:
              - not_null
          - name: impression
            tests:
              - not_null
          - name: click
            tests:
              - not_null

      - name: finance_days
        description: finance calculation per days

      - name: finance_campaigns_day
        description: finance calculation per day plus marketing campaigns costs
        columns:
          - name: date_date
            tests:
              - unique
              - not_null
          - name: ads_cost
          - name: margin
          - name: average_basket
          - name: operational_margin
          - name: ads_margin